# Generated by Django 4.2.30 on 2026-06-24 19:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Email Verification",
                "verbose_name_plural": "Email Verifications",
                "db_table": "accounts_email_verification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("RESEARCHER", "Researcher"),
                            ("COMPANY_ADMIN", "Company Admin"),
                            ("TRIAGE_LEAD", "Triage Lead"),
                            ("ADMIN", "Platform Admin"),
                        ],
                        default="RESEARCHER",
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("is_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
                "db_table": "accounts_invitation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login Successful"),
                            ("FAILED_LOGIN", "Login Failed"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGE", "Password Changed"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("2FA_ENABLED", "2FA Enabled"),
                            ("2FA_DISABLED", "2FA Disabled"),
                            ("ACCOUNT_DEACTIVATED", "Account Deactivated"),
                            ("ACCOUNT_REACTIVATED", "Account Reactivated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Security Event",
                "verbose_name_plural": "Security Events",
                "db_table": "accounts_security_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name="passwordreset",
            new_name="accounts_pa_token_0816b4_idx",
            old_name="accounts_pas_token_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordreset",
            new_name="accounts_pa_user_id_51c341_idx",
            old_name="accounts_pas_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="auth_user_email_ece7f7_idx",
            old_name="auth_user_email_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="auth_user_role_f90fd2_idx",
            old_name="auth_user_role_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="auth_user_is_acti_9dcf31_idx",
            old_name="auth_user_active_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="accounts_se_user_id_a7a6eb_idx",
            old_name="accounts_use_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="accounts_se_token_82d2d3_idx",
            old_name="accounts_use_token_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="invited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitations_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
